[package]
name = "ox_webservice_stream"
version = "0.0.1"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"
serde_json = "1.0"
ox_webservice_api = { path = "../ox_webservice_api" }
ox_fileproc = { path = "../ox_fileproc" }
regex = "1.12"

libc = "0.2"
reqwest = { version = "0.12", features = ["json"] }
tokio = { version = "1.36", features = ["full"] }
base64 = "0.21"
log4rs = "1.2.0"
log = "0.4"
anyhow = "1.0"
bumpalo = "3.19.0"

[dev-dependencies]
axum = "0.8.7"
bumpalo = "3.19.0"
cargo_metadata = "0.23.1"
libloading = "0.9.0"
once_cell = "1.21.3"
tempfile = "3.23.0"
ox_webservice_test_utils = { path = "../ox_webservice_test_utils" }
