[package]
name = "ox_event_bus_mqtt"
version = "0.1.0"
edition = "2021"

[dependencies]
ox_event_bus = { path = ".." }
rumqttc = "0.24"
tokio = { version = "1.0", features = ["full"] }
async-trait = "0.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
uuid = { version = "1.0", features = ["v4"] }
futures = "0.3"
tokio-stream = { version = "0.1", features = ["sync"] }
log = "0.4"
