[package]
name = "ox_persistence_datastore_drivermanager"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
libloading = "0.8"
libc = "0.2"
walkdir = "2.4" # Useful for scanning directories
ox_persistence = { path = "../" }

