[package]
name = "oxIDIZER"
version = "0.0.1"
edition = "2024"
resolver = "2"

[workspace]
members = [
    "ox_callback_manager",

    "ox_data_broker",
    "ox_data_object",
    "ox_data_object_manager", "ox_fileproc",
    "ox_locking",
    "ox_persistence",
    "ox_persistence_api",
    "ox_persistence_datastore_flatfile",
    "ox_persistence_gdo_relational",
    "ox_persistence_datastore_json",
    "ox_persistence_datastore_mssql",
    "ox_persistence_datastore_mysql",
    "ox_persistence_datastore_postgresql",
    "ox_persistence_sql",
    "ox_persistence_datastore_xml",
    "ox_persistence_datastore_yaml",
    "ox_type_converter",
    "ox_webservice",
    "ox_webservice_api",
    "ox_webservice_errorhandler_jinja2",
    "ox_webservice_stream",
    "ox_webservice_template_jinja2",
    "ox_webservice_forwarded_for",
    "ox_webservice_restore_ip",
]
