[package]
name = "oxIDIZER"
version = "0.0.1"
edition = "2024"
resolver = "2"

[workspace]
members = [
    "ox_callback_manager",

    "ox_data_broker",
    "ox_data_object",
    "ox_data_object_manager", "ox_fileproc",
    "ox_locking",
    "ox_persistence/ox_persistence_datastore_drivermanager/ox_persistence_datastore_drivermanager_wasm",
    "ox_persistence_gdo_relational",
    "ox_persistence/ox_persistence_api",
    "ox_persistence/drivers/file/ox_persistence_driver_file_delimited",
    "ox_persistence/drivers/file/ox_persistence_driver_file_json",
    "ox_persistence/drivers/file/ox_persistence_driver_file_xml",
    "ox_persistence/drivers/file/ox_persistence_driver_file_yaml",
    "ox_persistence/drivers/db/ox_persistence_driver_db_mssql",
    "ox_persistence/drivers/db/ox_persistence_driver_db_mysql",
    "ox_persistence/drivers/db/ox_persistence_driver_db_postgres",
    "ox_persistence/drivers/db/ox_persistence_driver_db_sql",
    "ox_persistence/drivers/db/ox_persistence_driver_db_sqlite",
    "ox_persistence/ox_persistence_datastore_drivermanager",
    "ox_type_converter",
    "ox_webservice",
    "ox_webservice_api",
    "ox_webservice_errorhandler_jinja2",
    "ox_webservice_stream",
    "ox_webservice_template_jinja2",
    "ox_webservice_forwarded_for",
    "ox_webservice_restore_ip",
    "ox_webservice_redirect",
    "ox_webservice_rewrite",
    "ox_webservice_status",
    "ox_webservice_test_utils",
    "ox_webservice_ping",
]

[dependencies]
ox_data_object = { path = "ox_data_object" }
ox_locking = { path = "ox_locking" }
ox_persistence = { path = "ox_persistence" }
ox_persistence_driver_db_sql = { path = "ox_persistence/drivers/db/ox_persistence_driver_db_sql" }
ox_persistence_driver_db_mysql = { path = "ox_persistence/drivers/db/ox_persistence_driver_db_mysql" }
ox_persistence_driver_file_json = { path = "ox_persistence/drivers/file/ox_persistence_driver_file_json" }
ox_persistence_driver_file_delimited = { path = "ox_persistence/drivers/file/ox_persistence_driver_file_delimited" }
ox_persistence_driver_db_mssql = { path = "ox_persistence/drivers/db/ox_persistence_driver_db_mssql" }
ox_persistence_driver_db_postgres = { path = "ox_persistence/drivers/db/ox_persistence_driver_db_postgres" }
ox_persistence_driver_file_xml = { path = "ox_persistence/drivers/file/ox_persistence_driver_file_xml" }
ox_persistence_driver_file_yaml = { path = "ox_persistence/drivers/file/ox_persistence_driver_file_yaml" }
serde_yaml = "0.9"
serde = { version = "1.0", features = ["derive"] }
ox_type_converter = { version = "0.1.0", path = "ox_type_converter" }
uuid = "1.19.0"

[dev-dependencies]
ox_persistence_driver_db_mysql = { path = "ox_persistence/drivers/db/ox_persistence_driver_db_mysql" }
ox_persistence_driver_file_json = { path = "ox_persistence/drivers/file/ox_persistence_driver_file_json" }
