[package]
name = "oxIDIZER"
version = "0.0.1"
edition = "2024"
resolver = "2"

[workspace]
members = [
    "ox_callback_manager",
    "ox_content",
    "ox_data_broker",
    "ox_data_object",
    "ox_data_object_manager",
    "ox_locking",
    "ox_persistence",
    "ox_persistence_api",
    "ox_persistence_flatfile",
    "ox_persistence_gdo_relational",
    "ox_persistence_json",
    "ox_persistence_mssql",
    "ox_persistence_mysql",
    "ox_persistence_postgresql",
    "ox_persistence_sql",
    "ox_persistence_xml",
    "ox_persistence_yaml",
    "ox_server_info",
    "ox_status_page",
    "ox_type_converter",
    "ox_webservice",
    "ox_webservice_api",
    "ox_webservice_errorhandler_jinja2",
]
