[package]
name = "ox_webservice_forwarded_for"
version = "0.0.1"
license = "GPL-3.0-only"
edition = "2024"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
libc = "0.2"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
ox_webservice_api = { path = "../ox_webservice_api" }
anyhow = "1.0"
bumpalo = "3.19.0"
ox_pipeline_plugin = { path = "../ox_pipeline/ox_pipeline_plugin" }

[dev-dependencies]
ox_webservice_test_utils = { path = "../ox_webservice_test_utils" }
axum = "0.7"
lazy_static = "1.5.0"
