[package]
name = "ox_webservice_test_utils"
version = "0.1.0"
edition = "2024"

[dependencies]
libc = "0.2"
bumpalo = "3.12"
axum = "0.7"
tokio = { version = "1.0", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
ox_webservice_api = { path = "../ox_webservice_api" }
