friendly_name: Delimited File
id: "delimited_datasource_form"
title: "Delimited File Data Source Configuration"
fields:
  - name: "path"
    label: "File Path"
    data_type: "string"
    default_value: "data/storage.csv"
    props:
      placeholder: "data/storage.csv"
    validation:
      - rule_type: "required"
  - name: "delimiter"
    label: "Delimiter"
    data_type: "string"
    default_value: ","
    props:
      placeholder: "e.g., , or | or \t"
    validation:
      - rule_type: "required"
styles: "overflow-y: auto; max-height: 70vh;"
actions:
  - name: "submit"
    label: "Save Data Source"
    action_type: "submit"
  - name: "cancel"
    label: "Cancel"
    action_type: "button"
    props:
      classes: "btn-light"
