[package]
name = "ox_webservice_vary_header"
version = "0.1.0"
license = "GPL-3.0-only"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
ox_webservice_api = { path = "../ox_webservice_api" }
log = "0.4"
axum = "0.7.9"

