[package]
name = "ox_webservice_api"
version = "0.0.1"
edition = "2024"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
libc = "0.2"
axum = { version = "0.7" }
tokio = { version = "1.36" }
bumpalo = "3.19.0"
log = { version = "0.4.29", features = ["std"] }
