[package]
name = "ox_status_page"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
minijinja = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
libc = "0.2"
ox_webservice = { path = "../ox_webservice" }
bumpalo = "3.19.0"
