[package]
name = "ox_persistence_driver_file_json"
version = "0.1.0"
license = "GPL-3.0-only"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
ox_persistence = { path = "../../../" }
ox_locking = { path = "../../../../ox_locking" }
ox_data_object = { path = "../../../../ox_data_object" }
ox_type_converter = { path = "../../../../ox_type_converter" }
ox_fileproc = { path = "../../../../ox_fileproc" }
libc = "0.2"
bumpalo = "3.19.0"

[dev-dependencies]
tempfile = "3.23.0"
