[package]
name = "ox_data_object"
version = "0.1.0"
edition = "2024"

[dependencies]
uuid = { version = "1.8.0", features = ["v4", "serde"] }
ox_type_converter = { path = "../ox_type_converter" }
serde = { version = "1.0", features = ["derive"] }
