
[[drivers]]
name = "ox_persistence_flatfile"

[[drivers]]
name = "ox_persistence_json"

[[drivers]]
name = "ox_persistence_mssql"

[[drivers]]
name = "ox_persistence_mysql"

[[drivers]]
name = "ox_persistence_postgresql"

[[drivers]]
name = "ox_persistence_driver_sql"

[[drivers]]
name = "ox_persistence_xml"

[[drivers]]
name = "ox_persistence_yaml"
