[package]
name = "ox_persistence_driver_file_yaml"
version = "0.1.0"
license = "GPL-3.0-only"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
ox_persistence = { path = "../../../" }
ox_locking = { path = "../../../../ox_locking" }
ox_data_object = { path = "../../../../ox_data_object" }
ox_type_converter = { path = "../../../../ox_type_converter" }
ox_fileproc = { path = "../../../../ox_fileproc" }
serde = { version = "1.0", features = ["derive"] }
# serde_yaml removed (using ox_fileproc)
libc = "0.2"
bumpalo = "3.19.0"
# serde_json removed (using ox_fileproc)

[dev-dependencies]
tempfile = "3.2"
