[package]
name = "ox_persistence_api"
version = "0.1.0"
edition = "2021"

[dependencies]
ox_persistence = { path = "../../" }
ox_locking = { path = "../../../ox_locking" }
ox_data_object = { path = "../../../ox_data_object" }
ox_type_converter = { path = "../../../ox_type_converter" }
serde = { version = "1.0", features = ["derive"] }
reqwest = { version = "0.11", features = ["json", "blocking"] }
tokio = { version = "1", features = ["full"] } # For async operations
libc = "0.2"
bumpalo = "3.19.0"
serde_json = "1.0"
