friendly_name: PostgreSQL
id: "postgres_datasource_form"
title: "PostgreSQL Data Source Configuration"
fields:
  - name: "host"
    label: "Host"
    data_type: "string"
    default_value: "localhost"
    props:
      placeholder: "localhost"
    validation:
      - rule_type: "required"
  - name: "port"
    label: "Port"
    data_type: "integer"
    default_value: 5432
  - name: "user"
    label: "Username"
    data_type: "string"
    validation:
      - rule_type: "required"
  - name: "password"
    label: "Password"
    data_type: "password"
    props:
      type: "password"
  - name: "dbname"
    label: "Database Name"
    data_type: "string"
    validation:
      - rule_type: "required"
styles: "overflow-y: auto; max-height: 70vh;"
actions:
  - name: "submit"
    label: "Save Data Source"
    action_type: "submit"
  - name: "cancel"
    label: "Cancel"
    action_type: "button"
    props:
      classes: "btn-light"
