[package]
name = "ox_forms_server"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
ox_forms = { path = ".." }
ox_webservice_api = { path = "../../ox_webservice_api" }
ox_pipeline_plugin = { path = "../../ox_pipeline/ox_pipeline_plugin" }
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
log = "0.4"
anyhow = "1.0"
http = "1.0"
