  - url: "[.]html$"
    mimetype: "text/html"
    module_id: "default_stream"
  - url: "[.]htm$"
    mimetype: "text/html"
    module_id: "default_stream"
  - url: "[.]css$"
    mimetype: "text/css"
    module_id: "default_stream"
  - url: "[.]js$"
    mimetype: "application/javascript"
    module_id: "default_stream"
  - url: "[.]png$"
    mimetype: "image/png"
    module_id: "default_stream"
  - url: "[.]jpg$"
    mimetype: "image/jpeg"
    module_id: "default_stream"
  - url: "[.]jpeg$"
    mimetype: "image/jpeg"
    module_id: "default_stream"
  - url: "[.]gif$"
    mimetype: "image/gif"
    module_id: "default_stream"
  - url: "[.]jinja$"
    mimetype: "text/html"
    module_id: "default_template_jinja2"
  - url: "[.]jinja2$"
    mimetype: "text/html"
    module_id: "default_template_jinja2"
