content_root: "/mnt/c/Users/justl/source/repos/oxDataObject/content/www"
mimetypes_file: "/mnt/c/Users/justl/source/repos/oxDataObject/mimetypes.yaml"
default_documents:
  - document: "index.jinja2"
  - document: "index.html"
  - document: "default.html"
