[package]
name = "ox_persistence_sql"
version = "0.1.0"
edition = "2021"

[dependencies]
ox_persistence = { path = "../ox_persistence" }
ox_type_converter = { path = "../ox_type_converter" }
libc = "0.2"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
