[package]
name = "ox_persistence_driver_db_sql"
version = "0.1.0"
license = "GPL-3.0-only"
edition = "2021"

[dependencies]
ox_persistence = { path = "../../../" }
ox_locking = { path = "../../../../ox_locking" }
ox_data_object = { path = "../../../../ox_data_object" }
ox_type_converter = { path = "../../../../ox_type_converter" }
libc = "0.2"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
