[package]
name = "ox_webservice_template_jinja2-fuzz"
version = "0.0.0"
publish = false
edition = "2024"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }

[dependencies.ox_webservice_template_jinja2]
path = ".."

[[bin]]
name = "config_parse"
path = "fuzz_targets/config_parse.rs"
test = false
doc = false
bench = false

[workspace]

