[package]
name = "ox_webservice_restore_ip"
version = "0.0.1"
edition = "2024"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
libc = "0.2"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
ox_webservice_api = { path = "../ox_webservice_api" }
ox_plugin = { path = "../ox_plugin" }
anyhow = "1.0"
bumpalo = "3.19.0"

[dev-dependencies]
axum = "0.7"
